name: Price Hunter Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  TerraformDeploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Change directory to terraform
        run: cd terraform

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="resource_group_name=${{ secrets.AZURE_RG }}" -backend-config="storage_account_name=${{ secrets.AZURE_SA }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  DeployApp:
    needs: TerraformDeploy
    runs-on: windows-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore PriceHunter/PriceHunter.csproj

      - name: Build
        run: dotnet build PriceHunter/PriceHunter.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test PriceHunter.Tests/PriceHunter.Tests.csproj --configuration Release --no-restore --logger="trx;LogFileName=test-results.trx"

      - name: Publish
        run: dotnet publish PriceHunter/PriceHunter.csproj --configuration Release --no-restore --output ./publish

      - name: Zip artifact for deployment
        run: Compress-Archive -Path ./publish/* -DestinationPath pricehunter.zip

      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: pricehunter.zip
