name: CI/CD Deploy Price Hunter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  TerraformDeploy:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_INFRADEPLOYMENT_CLIENTID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TERNSTROM_TENANTID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_TERNSTROM_SUBSCRIPTIONID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_INFRADEPLOYMENT_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TERNSTROM_TENANTID }}
          allow-no-subscriptions: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.9'
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var "resource_group_name=price-hunter-rg" -var "location=West Europe" -var "app_service_plan_name=price-hunter-plan" -var "web_app_name=price-hunter-webapp-${{ github.run_number }}"
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var "resource_group_name=price-hunter-rg" -var "location=West Europe" -var "app_service_plan_name=price-hunter-plan" -var "web_app_name=price-hunter-webapp-${{ github.run_number }}"

  DeployApp:
    name: Deploy Price Hunter Application
    runs-on: ubuntu-latest
    needs: TerraformDeploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_INFRADEPLOYMENT_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TERNSTROM_TENANTID }}
          allow-no-subscriptions: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      
      - name: Restore and Publish Price Hunter
        run: |
          dotnet restore
          dotnet publish -c Release -o publish
          
      - name: Archive Published Files
        run: |
          cd publish
          zip -r ../pricehunter.zip .
      
      - name: Deploy to Azure Web App via CLI
        run: |
          az webapp deployment source config-zip --resource-group price-hunter-rg --name price-hunter-webapp-${{ github.run_number }} --src pricehunter.zip
